# Generated by Django 5.1.2 on 2024-10-24 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coderr_app', '0004_alter_offers_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='offers',
            name='min_delivery_time',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='offers',
            name='min_price',
            field=models.DecimalField(decimal_places=2, default=1.0, max_digits=10),
        ),
    ]
