# Generated by Django 5.1.2 on 2024-10-24 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coderr_app', '0005_offers_min_delivery_time_offers_min_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offers',
            name='min_delivery_time',
        ),
        migrations.RemoveField(
            model_name='offers',
            name='min_price',
        ),
    ]
