# Generated by Django 5.1.2 on 2024-10-28 15:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coderr_app', '0010_alter_userprofile_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('revisions', models.IntegerField()),
                ('delivery_time_in_days', models.PositiveIntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('features', models.JSONField()),
                ('offer_type', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(max_length=25)),
                ('business_user', models.ForeignKey(limit_choices_to={'user_profile__type': 'business'}, on_delete=django.db.models.deletion.CASCADE, related_name='business_order', to=settings.AUTH_USER_MODEL)),
                ('customer_user', models.ForeignKey(limit_choices_to={'user_profile__type': 'customer'}, on_delete=django.db.models.deletion.CASCADE, related_name='customer_order', to=settings.AUTH_USER_MODEL)),
                ('offer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='coderr_app.offers')),
                ('offer_details', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='coderr_app.offerdetails')),
            ],
        ),
    ]
