# Generated by Django 5.1.2 on 2024-11-05 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coderr_app', '0014_alter_offerdetails_options_alter_offers_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userprofile',
            options={'ordering': ['user__username'], 'verbose_name_plural': 'User Profiles'},
        ),
    ]
